# -*- coding: utf-8 -*-
"""demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wJ9uhzcFzB4oe1VaAS5Mq_BKzuhjOoYb
"""

# @title Setup & Styles
import ipywidgets as widgets
from IPython.display import display, HTML

# Shared CSS Styles
GLOBAL_CSS = """
<style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');

    :root {
        --primary: #2ecc71;
        --primary-light: #e8f8f5;
        --text-dark: #2c3e50;
        --text-gray: #7f8c8d;
        --bg-color: #f8f9fa;
        --card-bg: #ffffff;
        --danger: #e74c3c;
        --warning: #f1c40f;
        --success: #27ae60;
        --info: #3498db;
    }

    .dashboard-container {
        font-family: 'Inter', sans-serif;
        background-color: var(--bg-color);
        padding: 20px;
        border-radius: 12px;
        color: var(--text-dark);
        max-width: 1200px;
        margin: 0 auto;
        min-height: 800px;
    }

    /* Header */
    .header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 24px;
        padding-bottom: 16px;
        border-bottom: 1px solid #eee;
    }
    .brand {
        font-size: 20px;
        font-weight: 700;
        color: var(--text-dark);
        display: flex;
        align-items: center;
        gap: 10px;
    }
    .brand-icon {
        background: var(--primary);
        color: white;
        width: 32px;
        height: 32px;
        border-radius: 50%;
        display: flex;
        align-items: center;
        justify-content: center;
        font-size: 18px;
    }
    .nav-menu {
        display: flex;
        gap: 20px;
        font-size: 14px;
        color: var(--text-gray);
    }
    .nav-item {
        cursor: pointer;
        display: flex;
        align-items: center;
        gap: 6px;
        padding: 6px 12px;
        border-radius: 20px;
        transition: all 0.2s;
    }
    .nav-item:hover {
        background: #f0f0f0;
    }
    .nav-item.active {
        background: #d1f2eb;
        color: var(--success);
        font-weight: 600;
    }

    /* Common Layouts */
    .grid-3 {
        display: grid;
        grid-template-columns: repeat(3, 1fr);
        gap: 20px;
        margin-bottom: 20px;
    }
    .grid-2 {
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        gap: 20px;
        margin-bottom: 20px;
    }
    .grid-1-2 {
        display: grid;
        grid-template-columns: 1fr 2fr;
        gap: 20px;
        margin-bottom: 20px;
    }

    /* Cards */
    .card {
        background: var(--card-bg);
        border-radius: 16px;
        padding: 20px;
        box-shadow: 0 2px 10px rgba(0,0,0,0.03);
        border: 1px solid #f0f0f0;
        height: 100%;
        box-sizing: border-box;
        position: relative;
    }
    .card-title {
        font-size: 14px;
        font-weight: 600;
        color: var(--text-dark);
        margin-bottom: 16px;
    }

    /* Buttons */
    .btn {
        padding: 10px 20px;
        border-radius: 8px;
        font-weight: 600;
        font-size: 14px;
        cursor: pointer;
        border: none;
        display: flex;
        align-items: center;
        gap: 8px;
        justify-content: center;
        transition: opacity 0.2s;
    }
    .btn:hover {
        opacity: 0.9;
    }
    .btn-primary {
        background: var(--primary);
        color: white;
        box-shadow: 0 2px 6px rgba(46, 204, 113, 0.3);
    }
    .btn-outline {
        background: white;
        border: 1px solid #ddd;
        color: var(--text-dark);
    }
    .btn-full {
        width: 100%;
    }

    /* Typography */
    .text-success { color: var(--success); }
    .text-warning { color: var(--warning); }
    .text-danger { color: var(--danger); }
    .text-gray { color: var(--text-gray); }
    .font-bold { font-weight: 700; }

    /* Specific Components */
    .status-badge {
        padding: 4px 8px;
        border-radius: 12px;
        font-size: 12px;
        font-weight: 600;
    }
    .badge-success { background: #eafaf1; color: var(--success); }
    .badge-warning { background: #fef9e7; color: var(--warning); }

</style>
"""

# @title Shared Data

# @title Shared Data
# Unified Mock Data Structure (Firebase/MQTT Style)

# 1. Plants Data
PLANTS_DATA = {
    "plant_01": {
        "name": "Monstera Deliciosa",
        "species": "Indoor Plant",
        "image": "🌿",
        "health": 85,
        "health_label": "Excellent",
        "targets": {
            "moisture": "60-70%",
            "temperature": "18-24°C",
            "light": "High"
        },
        "sensor_ids": {
            "moisture": "sensor_m_01",
            "temperature": "sensor_t_01",
            "light": "sensor_l_01"
        },
        "alerts": [
            {"type": "warning", "msg": "Soil drying out", "sub": "Water recommended within 24h", "time": "2h ago"},
            {"type": "success", "msg": "Temperature optimal", "sub": "Between 18-24°C", "time": "5h ago"}
        ]
    },
    "plant_02": {
        "name": "Snake Plant",
        "species": "Succulent",
        "image": "🪴",
        "health": 92,
        "health_label": "Perfect",
        "targets": {
            "moisture": "30-40%",
            "temperature": "20-30°C",
            "light": "Medium"
        },
        "sensor_ids": {
            "moisture": "sensor_m_02",
            "temperature": "sensor_t_02",
            "light": "sensor_l_02"
        },
        "alerts": [
            {"type": "success", "msg": "All systems nominal", "sub": "Plant is thriving", "time": "1h ago"}
        ]
    }
}

# 2. Sensor Data
SENSORS_DATA = {
    "sensor_m_01": {
        "type": "moisture",
        "name": "Moisture",
        "value": 65,
        "unit": "%",
        "icon": "💧",
        "status": "Optimal",
        "status_class": "badge-success",
        "target": "60-70%",
        "history": "0,60 50,58 100,55 150,70 200,80 250,85 300,80 350,75 400,60",
        "metadata": {
            "mqtt_topic": "plant/plant_01/moisture",
            "hardware": "ESP32 + Capacitive Probe",
            "last_calibrated": "2025-01-10"
        },
        "thresholds": {
            "min": 0,
            "max": 100,
            "warning_below": 50,
            "danger_below": 30
        }
    },
    "sensor_t_01": {
        "type": "temperature",
        "name": "Temperature",
        "value": 22,
        "unit": "°C",
        "icon": "🌡️",
        "status": "Optimal",
        "status_class": "badge-success",
        "target": "18-24°C",
        "history": "0,20 50,20 100,21 150,22 200,24 250,25 300,24 350,22 400,21",
        "metadata": {
            "mqtt_topic": "plant/plant_01/temperature",
            "hardware": "DHT22",
            "last_calibrated": "2025-01-15"
        },
        "thresholds": {
            "min": 0,
            "max": 50,
            "warning_below": 15,
            "danger_below": 10
        }
    },
    "sensor_l_01": {
        "type": "light",
        "name": "Light Level",
        "value": "High",
        "unit": "",
        "icon": "☀️",
        "status": "Good",
        "status_class": "badge-success",
        "target": "High",
        "history": "",
        "metadata": {
            "mqtt_topic": "plant/plant_01/light",
            "hardware": "BH1750",
            "last_calibrated": "2025-01-05"
        },
        "thresholds": {
            "min": 0,
            "max": 1000,
            "warning_below": 200,
            "danger_below": 100
        }
    },
    "sensor_m_02": {
        "type": "moisture",
        "name": "Moisture",
        "value": 40,
        "unit": "%",
        "icon": "💧",
        "status": "Optimal",
        "status_class": "badge-success",
        "target": "30-40%",
        "history": "0,40 100,38 200,35 300,42 400,40",
        "metadata": {
            "mqtt_topic": "plant/plant_02/moisture",
            "hardware": "ESP32 + Capacitive Probe",
            "last_calibrated": "2025-02-01"
        },
        "thresholds": {
            "min": 0,
            "max": 100,
            "warning_below": 30,
            "danger_below": 20
        }
    },
    "sensor_t_02": {
        "type": "temperature",
        "name": "Temperature",
        "value": 24,
        "unit": "°C",
        "icon": "🌡️",
        "status": "Optimal",
        "status_class": "badge-success",
        "target": "20-30°C",
        "history": "0,22 100,23 200,24 300,25 400,24",
        "metadata": {
            "mqtt_topic": "plant/plant_02/temperature",
            "hardware": "DHT22",
            "last_calibrated": "2025-02-01"
        },
        "thresholds": {
            "min": 0,
            "max": 50,
            "warning_below": 15,
            "danger_below": 10
        }
    },
    "sensor_l_02": {
        "type": "light",
        "name": "Light Level",
        "value": "Medium",
        "unit": "",
        "icon": "☀️",
        "status": "Good",
        "status_class": "badge-success",
        "target": "Medium",
        "history": "",
        "metadata": {
            "mqtt_topic": "plant/plant_02/light",
            "hardware": "BH1750",
            "last_calibrated": "2025-02-01"
        },
        "thresholds": {
            "min": 0,
            "max": 1000,
            "warning_below": 200,
            "danger_below": 100
        }
    }
}

# 3. Analysis Data
ANALYSIS_DATA = {
    "plant_01": {
        "latest": {
            "issues": [
                {"type": "warning", "title": "Leaf yellowing detected", "desc": "Lower leaves showing signs of nitrogen deficiency", "icon": "⚠️", "color": "#f1c40f", "bg": "#fef9e7", "severity": "Medium"},
                {"type": "info", "title": "Minor brown spots", "desc": "Could indicate inconsistent watering", "icon": "ℹ️", "color": "#3498db", "bg": "#e8f8f5", "severity": "Low"}
            ],
            "confidence": 87,
            "recommendations": ["Apply nitrogen-rich fertilizer", "Maintain consistent watering schedule", "Monitor over next 7 days"]
        },
        "history": [
            {"date": "2 days ago", "summary": "Healthy - No issues", "thumb": "🌿"},
            {"date": "1 week ago", "summary": "Minor wilting", "thumb": "🥀"},
            {"date": "2 weeks ago", "summary": "Healthy - No issues", "thumb": "🌿"},
        ]
    },
    "plant_02": {
        "latest": {
            "issues": [],
            "confidence": 90,
            "recommendations": []
        },
        "history": [
            {"date": "2 days ago", "summary": "Healthy - No issues", "thumb": "🌿"}
        ]
    }
}

# @title Home Page

# Components
def create_plant_card(plant):
    return widgets.HTML(f"""
    <div class='card'>
        <div class='card-title'>Current Plant</div>
        <div class='plant-image-box' style='background: #d5f5e3; border-radius: 12px; height: 180px; display: flex; align-items: center; justify-content: center; font-size: 80px; margin-bottom: 16px;'>
            {plant['image']}
        </div>
        <div class='plant-name' style='font-size: 18px; font-weight: 700; color: #2c3e50;'>{plant['name']}</div>
        <div class='plant-type' style='font-size: 13px; color: #7f8c8d;'>{plant['species']}</div>
    </div>
    """)

def create_health_card(plant):
    score = plant['health']
    color = "#2ecc71" if score > 80 else "#f1c40f" if score > 50 else "#e74c3c"
    dash_array = f"{score}, 100"

    svg = f"""
    <svg viewBox="0 0 36 36" style="display: block; margin: 0 auto; max-width: 80%; max-height: 250px;">
      <path style="fill: none; stroke: #eee; stroke-width: 3.8;"
        d="M18 2.0845
          a 15.9155 15.9155 0 0 1 0 31.831
          a 15.9155 15.9155 0 0 1 0 -31.831"
      />
      <path style="fill: none; stroke-width: 2.8; stroke-linecap: round; animation: progress 1s ease-out forwards;"
        stroke="{color}"
        stroke-dasharray="{dash_array}"
        d="M18 2.0845
          a 15.9155 15.9155 0 0 1 0 31.831
          a 15.9155 15.9155 0 0 1 0 -31.831"
      />
      <text x="18" y="20.35" style="fill: #2ecc71; font-family: 'Inter', sans-serif; font-weight: bold; font-size: 0.5em; text-anchor: middle;">{score}</text>
      <text x="18" y="25" style="fill: #7f8c8d; font-family: 'Inter', sans-serif; font-size: 0.15em; text-anchor: middle;">{plant['health_label']}</text>
    </svg>
    """

    return widgets.HTML(f"""
    <div class='card'>
        <div class='card-title'>Plant Health</div>
        <div style='display: flex; align-items: center; justify-content: center; height: 240px;'>
            {svg}
        </div>
    </div>
    """)

def create_sensor_card(plant):
    rows = ""
    # Look up sensors from global SENSORS_DATA
    for sensor_type, sensor_id in plant['sensor_ids'].items():
        if sensor_id in SENSORS_DATA:
            s = SENSORS_DATA[sensor_id]
            rows += f"""
            <div style='background: #e8f8f5; padding: 12px 16px; border-radius: 10px; margin-bottom: 12px; display: flex; justify-content: space-between; align-items: center;'>
                <div style='display: flex; align-items: center; gap: 10px; font-weight: 500; color: #2c3e50;'>
                    <span>{s['icon']}</span> {s['name']}
                </div>
                <div style='font-weight: 600; display: flex; align-items: center; gap: 8px;'>
                    {s['value']}{s['unit']} <div style='width: 8px; height: 8px; border-radius: 50%; background: #27ae60;'></div>
                </div>
            </div>
            """

    return widgets.HTML(f"""
    <div class='card'>
        <div class='card-title'>Sensor Status</div>
        {rows}
    </div>
    """)

def create_alerts_card(plant):
    rows = ""
    for a in plant['alerts']:
        icon = "⚠️" if a['type'] == 'warning' else "✓"
        bg_color = "#fef9e7" if a['type'] == 'warning' else "#eafaf1"
        border_color = "#f1c40f" if a['type'] == 'warning' else "#27ae60"

        rows += f"""
        <div style='padding: 12px; border-radius: 8px; margin-bottom: 10px; display: flex; justify-content: space-between; align-items: flex-start; background: {bg_color}; border-left: 4px solid {border_color};'>
            <div style='display: flex; gap: 10px;'>
                <div style='font-size:16px;'>{icon}</div>
                <div>
                    <div style='font-weight:600; font-size:13px;'>{a['msg']}</div>
                    <div style='font-size:11px; color:#666;'>{a['sub']}</div>
                </div>
            </div>
            <div style='font-size: 11px; color: #7f8c8d; white-space: nowrap;'>{a['time']}</div>
        </div>
        """

    return widgets.HTML(f"""
    <div class='card'>
        <div class='card-title'>Recent Alerts</div>
        {rows}
    </div>
    """)

def create_actions_card():
    return widgets.HTML("""
    <div class='card'>
        <div class='card-title'>Quick Actions</div>
        <div style='display: flex; gap: 12px; margin-top: 10px;'>
            <button class='btn btn-primary' style='flex:1;'>⚡ View Sensors</button>
            <button class='btn btn-outline' style='flex:1;'>📷 Analyze Image</button>
            <button class='btn btn-outline' style='flex:1;'>💬 Ask AI</button>
        </div>
    </div>
    """)

# Render
def render_home():
    # State
    current_plant_id = "plant_01"

    # Output area for dynamic content
    content = widgets.Output()

    def update_view(change=None):
        nonlocal current_plant_id
        if change:
            current_plant_id = change['new']

        plant = PLANTS_DATA[current_plant_id]

        # Grid 1: Top 3 cards
        c1 = create_plant_card(plant)
        c2 = create_health_card(plant)
        c3 = create_sensor_card(plant)

        grid1 = widgets.GridBox([c1, c2, c3], layout=widgets.Layout(grid_template_columns='1fr 1fr 1fr', grid_gap='20px', margin='0 0 20px 0'))

        # Grid 2: Bottom 2 cards
        c4 = create_alerts_card(plant)
        c5 = create_actions_card()

        grid2 = widgets.GridBox([c4, c5], layout=widgets.Layout(grid_template_columns='1fr 1fr', grid_gap='20px'))

        content.clear_output()
        with content:
            display(grid1)
            display(grid2)

    # Selector
    selector_options = [(p['name'], k) for k, p in PLANTS_DATA.items()]
    selector = widgets.Dropdown(options=selector_options, value="plant_01", layout=widgets.Layout(width='300px'))
    selector.observe(update_view, names='value')

    # Top Bar with Selector
    top_bar = widgets.HBox(
        [widgets.HTML("<span style='font-weight:600; color:#2c3e50; margin-right:10px;'>Select Plant:</span>"), selector],
        layout=widgets.Layout(margin='0 0 20px 0')
    )

    # Initial render
    update_view()

    return widgets.VBox([top_bar, content])

# @title Plants Page

# Components for Plants Page

def create_plant_list_card(plant_id, plant):
    # Sensor summary
    sensors_html = ""
    for sid in plant['sensor_ids'].values():
        if sid in SENSORS_DATA:
            s = SENSORS_DATA[sid]
            sensors_html += f"""
            <div style='display: flex; flex-direction: column; align-items: center; gap: 4px;'>
                <div style='font-size: 14px;'>{s['icon']}</div>
                <div style='font-size: 11px; font-weight: 600; color: #2c3e50;'>{s['value']}{s['unit']}</div>
            </div>
            """

    return widgets.HTML(f"""
    <div class='card plant-list-card' data-id='{plant_id}' style='cursor: pointer; transition: transform 0.2s;'>
        <div style='display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 15px;'>
            <div style='background: #d5f5e3; width: 60px; height: 60px; border-radius: 12px; display: flex; align-items: center; justify-content: center; font-size: 30px;'>
                {plant['image']}
            </div>
            <div class='status-badge badge-success'>{plant['health']}% Health</div>
        </div>
        <div style='font-weight: 700; color: #2c3e50; font-size: 16px; margin-bottom: 4px;'>{plant['name']}</div>
        <div style='font-size: 12px; color: #7f8c8d; margin-bottom: 15px;'>{plant['species']}</div>

        <div style='display: flex; justify-content: space-around; background: #f8f9fa; padding: 10px; border-radius: 8px;'>
            {sensors_html}
        </div>
    </div>
    """)

def create_add_plant_button():
    return widgets.HTML("""
    <div class='card' style='display: flex; flex-direction: column; align-items: center; justify-content: center; height: 100%; border: 2px dashed #ddd; background: transparent; cursor: pointer; min-height: 200px;'>
        <div style='width: 50px; height: 50px; background: #f0f0f0; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 24px; color: #95a5a6; margin-bottom: 10px;'>+</div>
        <div style='font-weight: 600; color: #95a5a6;'>Add New Plant</div>
    </div>
    """)

# Plant Details Components
def create_plant_overview(plant):
    return widgets.HTML(f"""
    <div class='card'>
        <div style='display: flex; gap: 20px; align-items: center;'>
            <div style='background: #d5f5e3; width: 100px; height: 100px; border-radius: 16px; display: flex; align-items: center; justify-content: center; font-size: 50px;'>
                {plant['image']}
            </div>
            <div style='flex: 1;'>
                <div style='display: flex; justify-content: space-between; align-items: flex-start;'>
                    <div>
                        <div style='font-size: 24px; font-weight: 700; color: #2c3e50;'>{plant['name']}</div>
                        <div style='font-size: 14px; color: #7f8c8d; margin-top: 4px;'>{plant['species']}</div>
                    </div>
                    <button class='btn btn-outline' style='padding: 6px 12px; font-size: 12px;'>✏️ Edit Plant</button>
                </div>
                <div style='margin-top: 15px; display: flex; gap: 10px;'>
                    <div class='status-badge badge-success' style='font-size: 14px; padding: 6px 12px;'>Health: {plant['health']}%</div>
                    <div class='status-badge badge-success' style='font-size: 14px; padding: 6px 12px; background: #e8f8f5; color: #2ecc71;'>{plant['health_label']}</div>
                </div>
            </div>
        </div>
    </div>
    """)

def create_sensor_assignment(plant):
    rows = ""
    for type_key, sid in plant['sensor_ids'].items():
        if sid in SENSORS_DATA:
            s = SENSORS_DATA[sid]
            rows += f"""
            <tr style='border-bottom: 1px solid #eee;'>
                <td style='padding: 12px; display: flex; align-items: center; gap: 10px;'>
                    <span>{s['icon']}</span> {s['name']}
                </td>
                <td style='padding: 12px; font-family: monospace; color: #7f8c8d;'>{sid}</td>
                <td style='padding: 12px;'><span class='status-badge {s['status_class']}'>{s['status']}</span></td>
                <td style='padding: 12px; text-align: right;'>
                    <button class='btn btn-outline' style='padding: 4px 10px; font-size: 11px; display: inline-flex;'>Change</button>
                </td>
            </tr>
            """

    return widgets.HTML(f"""
    <div class='card'>
        <div class='card-title'>Sensor Assignments</div>
        <table style='width: 100%; border-collapse: collapse; font-size: 14px;'>
            <thead style='background: #f8f9fa; color: #7f8c8d; font-size: 12px; text-transform: uppercase;'>
                <tr>
                    <th style='padding: 10px; text-align: left;'>Sensor Type</th>
                    <th style='padding: 10px; text-align: left;'>ID</th>
                    <th style='padding: 10px; text-align: left;'>Status</th>
                    <th style='padding: 10px; text-align: right;'>Action</th>
                </tr>
            </thead>
            <tbody>
                {rows}
            </tbody>
        </table>
    </div>
    """)

def create_readings_summary(plant):
    cards = ""
    for sid in plant['sensor_ids'].values():
        if sid in SENSORS_DATA:
            s = SENSORS_DATA[sid]
            cards += f"""
            <div style='background: #f8f9fa; padding: 15px; border-radius: 12px; flex: 1;'>
                <div style='display: flex; justify-content: space-between; margin-bottom: 10px;'>
                    <div style='font-size: 12px; color: #7f8c8d;'>{s['name']}</div>
                    <div>{s['icon']}</div>
                </div>
                <div style='font-size: 20px; font-weight: 700; color: #2c3e50;'>{s['value']}{s['unit']}</div>
                <div style='font-size: 11px; color: #27ae60; margin-top: 4px;'>Target: {s['target']}</div>
            </div>
            """

    return widgets.HTML(f"""
    <div class='card'>
        <div class='card-title'>Latest Readings</div>
        <div style='display: flex; gap: 15px;'>
            {cards}
        </div>
    </div>
    """)

def create_analysis_history_list(plant_id):
    # Mock lookup
    history = []
    if plant_id in ANALYSIS_DATA:
        history = ANALYSIS_DATA[plant_id]['history']

    rows = ""
    for item in history:
        rows += f"""
        <div style='display: flex; gap: 12px; padding: 12px 0; border-bottom: 1px solid #eee; align-items: center;'>
            <div style='width: 40px; height: 40px; background: #f0f0f0; border-radius: 8px; display: flex; align-items: center; justify-content: center; font-size: 20px;'>
                {item['thumb']}
            </div>
            <div style='flex: 1;'>
                <div style='font-size: 14px; font-weight: 600; color: #2c3e50;'>{item['summary']}</div>
                <div style='font-size: 12px; color: #95a5a6;'>{item['date']}</div>
            </div>
            <div style='color: #3498db; font-size: 12px; cursor: pointer;'>View ></div>
        </div>
        """

    return widgets.HTML(f"""
    <div class='card'>
        <div style='display: flex; justify-content: space-between; align-items: center; margin-bottom: 15px;'>
            <div class='card-title' style='margin-bottom: 0;'>Analysis History</div>
            <div style='font-size: 12px; color: #3498db; cursor: pointer;'>View All History</div>
        </div>
        <div>
            {rows}
        </div>
    </div>
    """)

def create_plant_alerts(plant):
    rows = ""
    for a in plant['alerts']:
        icon = "⚠️" if a['type'] == 'warning' else "✓"
        bg_color = "#fef9e7" if a['type'] == 'warning' else "#eafaf1"
        border_color = "#f1c40f" if a['type'] == 'warning' else "#27ae60"

        rows += f"""
        <div style='padding: 12px; border-radius: 8px; margin-bottom: 10px; display: flex; justify-content: space-between; align-items: flex-start; background: {bg_color}; border-left: 4px solid {border_color};'>
            <div style='display: flex; gap: 10px;'>
                <div style='font-size:16px;'>{icon}</div>
                <div>
                    <div style='font-weight:600; font-size:13px;'>{a['msg']}</div>
                    <div style='font-size:11px; color:#666;'>{a['sub']}</div>
                </div>
            </div>
            <div style='font-size: 11px; color: #7f8c8d; white-space: nowrap;'>{a['time']}</div>
        </div>
        """

    return widgets.HTML(f"""
    <div class='card'>
        <div class='card-title'>Active Alerts</div>
        {rows}
    </div>
    """)

# Render
def render_plants_page():
    # State
    view_mode = "list" # list or details
    selected_plant_id = None

    content = widgets.Output()

    def show_list():
        nonlocal view_mode, selected_plant_id
        view_mode = "list"
        selected_plant_id = None

        # Create grid of plants
        plant_cards = []
        for pid, p in PLANTS_DATA.items():
            card_html = create_plant_list_card(pid, p)

            btn = widgets.Button(description="View Details", layout=widgets.Layout(width='100%', margin='10px 0 0 0'))
            btn.style.button_color = '#e8f8f5'
            btn.style.text_color = '#2ecc71'

            # Closure to capture pid
            def on_click(b, pid=pid):
                show_details(pid)

            btn.on_click(on_click)

            plant_cards.append(widgets.VBox([card_html, btn]))

        # Add "Add Plant" button
        add_btn = create_add_plant_button()
        plant_cards.append(add_btn)

        grid = widgets.GridBox(plant_cards, layout=widgets.Layout(grid_template_columns='repeat(auto-fill, minmax(300px, 1fr))', grid_gap='20px'))

        header = widgets.HTML("""
        <div style='margin-bottom: 20px;'>
            <div style='font-size: 24px; font-weight: 700; color: #2c3e50;'>My Plants</div>
            <div style='color: #7f8c8d;'>Manage your garden and sensors</div>
        </div>
        """)

        content.clear_output()
        with content:
            display(widgets.VBox([header, grid]))

    def show_details(pid):
        nonlocal view_mode, selected_plant_id
        view_mode = "details"
        selected_plant_id = pid
        plant = PLANTS_DATA[pid]

        # Back button
        back_btn = widgets.Button(description="← Back to Plants", layout=widgets.Layout(width='150px'))
        back_btn.on_click(lambda b: show_list())

        # Components
        overview = create_plant_overview(plant)
        readings = create_readings_summary(plant)
        sensors = create_sensor_assignment(plant)
        history = create_analysis_history_list(pid)
        alerts = create_plant_alerts(plant)

        # Layout
        # Left col: Overview, Readings, Sensors
        left_col = widgets.VBox([overview, readings, sensors], layout=widgets.Layout(grid_gap='20px'))

        # Right col: Alerts, History
        right_col = widgets.VBox([alerts, history], layout=widgets.Layout(grid_gap='20px'))

        grid = widgets.GridBox([left_col, right_col], layout=widgets.Layout(grid_template_columns='2fr 1fr', grid_gap='20px'))

        content.clear_output()
        with content:
            display(widgets.VBox([back_btn, grid]))

    # Initial render
    show_list()

    return content

# @title Sensors Page

# Components
def create_gauge(data, on_click):
    title = data['name']
    value = data['value']
    unit = data['unit']
    # Mock min/max based on type for demo purposes
    min_val = 0
    max_val = 100
    if data['type'] == 'temperature':
        max_val = 50
    elif data['type'] == 'light':
        max_val = 1000
        if value == 'High': value = 850
        elif value == 'Medium': value = 500
        elif value == 'Low': value = 200
        else: value = 0

    color = "#2ecc71" # Default success
    if data['type'] == 'light': color = "#3498db"

    target_range = data['target']
    status = data['status']
    status_class = data['status_class']

    # Calculate percent
    if isinstance(value, int) or isinstance(value, float):
        percent = int(((value - min_val) / (max_val - min_val)) * 100)
    else:
        percent = 80 # Default for non-numeric

    percent = max(0, min(100, percent))

    dash_array = f"{percent}, 100"

    svg = f"""
    <svg viewBox="0 0 36 36" style="display: block; margin: 0 auto; max-width: 150px;">
      <path style="fill: none; stroke: #eee; stroke-width: 3;"
        d="M18 2.0845
          a 15.9155 15.9155 0 0 1 0 31.831
          a 15.9155 15.9155 0 0 1 0 -31.831"
      />
      <path style="fill: none; stroke-width: 3; stroke-linecap: round; animation: progress 1s ease-out forwards;"
        stroke="{color}"
        stroke-dasharray="{dash_array}"
        d="M18 2.0845
          a 15.9155 15.9155 0 0 1 0 31.831
          a 15.9155 15.9155 0 0 1 0 -31.831"
      />
      <text x="18" y="20" style="fill: #2c3e50; font-family: 'Inter', sans-serif; font-weight: bold; font-size: 0.5em; text-anchor: middle;">{data['value']}{unit}</text>
      <text x="18" y="25" style="fill: #7f8c8d; font-family: 'Inter', sans-serif; font-size: 0.15em; text-anchor: middle;">Target: {target_range}</text>
    </svg>
    """

    # Components
    title_widget = widgets.HTML(f"<div class='card-title'>{title}</div>")

    svg_widget = widgets.HTML(f"""
    <div style='display: flex; flex-direction: column; align-items: center; justify-content: center;'>
        {svg}
        <div class='status-badge {status_class}' style='margin-top: 10px;'>{status}</div>
    </div>
    """)

    details_btn = widgets.Button(
        description="Details >",
        layout=widgets.Layout(width='auto', margin='15px 0 0 0')
    )
    # Style to look like a link
    details_btn.style.button_color = 'transparent'
    details_btn.style.text_color = '#3498db'
    details_btn.style.font_weight = 'bold'

    # Remove border/shadow via custom class or just rely on transparent bg
    # ipywidgets buttons usually have a border. We can try to hide it with CSS injection or just accept a minimal border.
    # For "exactly like blue", we want no border.
    details_btn.add_class('btn-link-style')

    details_btn.on_click(on_click)

    # Container
    card = widgets.VBox(
        [title_widget, svg_widget, details_btn],
        layout=widgets.Layout(
            align_items='center',
            justify_content='space-between',
            height='250px', # Fixed height for consistency
            padding='20px'
        )
    )
    card.add_class('card')

    return card

def create_history_chart(data):
    # Mock history data parsing
    points_moisture = "0,60 50,58 100,55 150,70 200,80 250,85 300,80 350,75 400,60"
    points_temp = "0,20 50,20 100,21 150,22 200,24 250,25 300,24 350,22 400,21"

    svg = f"""
    <svg viewBox="0 0 400 100" style="width: 100%; height: 200px; overflow: visible;">
        <!-- Grid -->
        <line x1="0" y1="0" x2="400" y2="0" stroke="#eee" stroke-width="1" />
        <line x1="0" y1="25" x2="400" y2="25" stroke="#eee" stroke-width="1" stroke-dasharray="4" />
        <line x1="0" y1="50" x2="400" y2="50" stroke="#eee" stroke-width="1" stroke-dasharray="4" />
        <line x1="0" y1="75" x2="400" y2="75" stroke="#eee" stroke-width="1" stroke-dasharray="4" />
        <line x1="0" y1="100" x2="400" y2="100" stroke="#eee" stroke-width="1" />

        <!-- Lines -->
        <polyline points="{points_moisture}" fill="none" stroke="#2ecc71" stroke-width="2" />
        <polyline points="{points_temp}" fill="none" stroke="#3498db" stroke-width="2" />

        <!-- Labels -->
        <text x="0" y="115" fill="#999" font-size="10">00:00</text>
        <text x="100" y="115" fill="#999" font-size="10">04:00</text>
        <text x="200" y="115" fill="#999" font-size="10">08:00</text>
        <text x="300" y="115" fill="#999" font-size="10">12:00</text>
        <text x="380" y="115" fill="#999" font-size="10">16:00</text>
    </svg>
    """

    return widgets.HTML(f"""
    <div class='card'>
        <div style='display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px;'>
            <div class='card-title' style='margin-bottom: 0;'>24-Hour History</div>
            <div style='display: flex; gap: 5px;'>
                <button class='btn btn-outline' style='padding: 4px 12px; font-size: 12px; background: #f8f9fa;'>24h</button>
                <button class='btn btn-outline' style='padding: 4px 12px; font-size: 12px;'>7d</button>
                <button class='btn btn-outline' style='padding: 4px 12px; font-size: 12px;'>30d</button>
            </div>
        </div>

        <div style='padding: 20px 0;'>
            {svg}
        </div>

        <div style='display: flex; justify-content: center; gap: 20px; margin-top: 10px;'>
            <div style='display: flex; align-items: center; gap: 6px; font-size: 12px; color: #7f8c8d;'>
                <div style='width: 10px; height: 10px; background: #2ecc71; border-radius: 50%;'></div> Moisture
            </div>
            <div style='display: flex; align-items: center; gap: 6px; font-size: 12px; color: #7f8c8d;'>
                <div style='width: 10px; height: 10px; background: #3498db; border-radius: 50%;'></div> Temperature
            </div>
        </div>
    </div>
    """)

def create_summary_card(data):
    return widgets.HTML(f"""
    <div class='card'>
        <div class='card-title'>Summary</div>
        <div style='margin-bottom: 20px;'>
            <div style='font-size: 12px; color: #7f8c8d;'>Last Updated</div>
            <div style='font-weight: 600;'>2 min ago</div>
        </div>
        <div style='margin-bottom: 20px;'>
            <div style='font-size: 12px; color: #7f8c8d;'>Data Points</div>
            <div style='font-weight: 600;'>144/day</div>
        </div>
        <div>
            <div style='font-size: 12px; color: #7f8c8d;'>Overall Status</div>
            <div class='status-badge badge-success' style='display: inline-block; margin-top: 5px;'>All Good</div>
        </div>
    </div>
    """)

# Sensor Details Components
def create_sensor_header(sensor, sid):
    return widgets.HTML(f"""
    <div class='card' style='margin-bottom: 20px;'>
        <div style='display: flex; justify-content: space-between; align-items: center;'>
            <div style='display: flex; align-items: center; gap: 15px;'>
                <div style='font-size: 32px;'>{sensor['icon']}</div>
                <div>
                    <div style='font-size: 20px; font-weight: 700; color: #2c3e50;'>{sensor['name']}</div>
                    <div style='font-size: 12px; color: #7f8c8d; font-family: monospace;'>{sid}</div>
                </div>
            </div>
            <div style='text-align: right;'>
                <div class='status-badge {sensor['status_class']}'>{sensor['status']}</div>
                <div style='font-size: 11px; color: #7f8c8d; margin-top: 5px;'>Online</div>
            </div>
        </div>
    </div>
    """)

def create_realtime_card(sensor):
    return widgets.HTML(f"""
    <div class='card'>
        <div class='card-title'>Real-Time Reading</div>
        <div style='display: flex; flex-direction: column; align-items: center; justify-content: center; height: 150px;'>
            <div style='font-size: 48px; font-weight: 700; color: #2c3e50;'>{sensor['value']}{sensor['unit']}</div>
            <div style='font-size: 14px; color: #27ae60; margin-top: 5px;'>Target: {sensor['target']}</div>
            <div style='font-size: 11px; color: #95a5a6; margin-top: 15px;'>Last updated: 2 min ago</div>
        </div>
    </div>
    """)

def create_thresholds_card(sensor):
    t = sensor.get('thresholds', {'min': 0, 'max': 100, 'warning_below': 20, 'danger_below': 10})
    return widgets.HTML(f"""
    <div class='card'>
        <div class='card-title'>Thresholds</div>
        <div style='display: flex; flex-direction: column; gap: 10px;'>
            <div style='display: flex; justify-content: space-between; font-size: 13px;'>
                <span style='color: #7f8c8d;'>Max Allowed</span>
                <span style='font-weight: 600;'>{t['max']}</span>
            </div>
            <div style='display: flex; justify-content: space-between; font-size: 13px;'>
                <span style='color: #7f8c8d;'>Min Allowed</span>
                <span style='font-weight: 600;'>{t['min']}</span>
            </div>
            <div style='height: 1px; background: #eee; margin: 5px 0;'></div>
            <div style='display: flex; justify-content: space-between; font-size: 13px;'>
                <span style='color: #f1c40f;'>Warning Below</span>
                <span style='font-weight: 600; color: #f1c40f;'>{t['warning_below']}</span>
            </div>
            <div style='display: flex; justify-content: space-between; font-size: 13px;'>
                <span style='color: #e74c3c;'>Danger Below</span>
                <span style='font-weight: 600; color: #e74c3c;'>{t['danger_below']}</span>
            </div>
        </div>
    </div>
    """)

def create_mqtt_card(sensor):
    meta = sensor.get('metadata', {})
    topic = meta.get('mqtt_topic', 'N/A')
    payload = f'{{ "value": {sensor["value"]}, "unit": "{sensor["unit"]}" }}'
    return widgets.HTML(f"""
    <div class='card'>
        <div class='card-title'>MQTT Information</div>
        <div style='margin-bottom: 15px;'>
            <div style='font-size: 11px; color: #7f8c8d; text-transform: uppercase;'>Topic</div>
            <div style='font-family: monospace; background: #f8f9fa; padding: 8px; border-radius: 6px; font-size: 12px; margin-top: 4px;'>{topic}</div>
        </div>
        <div>
            <div style='font-size: 11px; color: #7f8c8d; text-transform: uppercase;'>Last Payload</div>
            <div style='font-family: monospace; background: #f8f9fa; padding: 8px; border-radius: 6px; font-size: 12px; margin-top: 4px;'>{payload}</div>
        </div>
    </div>
    """)

def create_metadata_card(sensor):
    meta = sensor.get('metadata', {})
    return widgets.HTML(f"""
    <div class='card'>
        <div class='card-title'>Device Metadata</div>
        <div style='display: grid; grid-template-columns: 1fr 1fr; gap: 15px;'>
            <div>
                <div style='font-size: 11px; color: #7f8c8d;'>Sensor Type</div>
                <div style='font-weight: 600; font-size: 13px;'>{sensor['type'].title()}</div>
            </div>
            <div>
                <div style='font-size: 11px; color: #7f8c8d;'>Hardware</div>
                <div style='font-weight: 600; font-size: 13px;'>{meta.get('hardware', 'Unknown')}</div>
            </div>
            <div>
                <div style='font-size: 11px; color: #7f8c8d;'>Last Calibrated</div>
                <div style='font-weight: 600; font-size: 13px;'>{meta.get('last_calibrated', 'N/A')}</div>
            </div>
            <div>
                <div style='font-size: 11px; color: #7f8c8d;'>Firmware</div>
                <div style='font-weight: 600; font-size: 13px;'>v2.1.0</div>
            </div>
        </div>
    </div>
    """)

def create_single_sensor_chart(sensor):
    # Mock single line chart
    points = "0,50 50,55 100,52 150,60 200,65 250,62 300,60 350,58 400,55"
    color = "#2ecc71" if sensor['type'] != 'light' else "#3498db"

    svg = f"""
    <svg viewBox="0 0 400 100" style="width: 100%; height: 200px; overflow: visible;">
        <polyline points="{points}" fill="none" stroke="{color}" stroke-width="2" />
        <!-- Grid -->
        <line x1="0" y1="0" x2="400" y2="0" stroke="#eee" stroke-width="1" />
        <line x1="0" y1="100" x2="400" y2="100" stroke="#eee" stroke-width="1" />
        <!-- Labels -->
        <text x="0" y="115" fill="#999" font-size="10">00:00</text>
        <text x="380" y="115" fill="#999" font-size="10">Now</text>
    </svg>
    """
    return widgets.HTML(f"""
    <div class='card'>
        <div class='card-title'>History Graph</div>
        <div style='padding: 10px 0;'>{svg}</div>
    </div>
    """)

# Render
def render_sensors():
    # State
    view_mode = "list" # list or details
    selected_sensor_id = None

    content = widgets.Output()

    def show_list():
        nonlocal view_mode, selected_sensor_id
        view_mode = "list"
        selected_sensor_id = None

        # Plant Selector (Static for now)
        plant_selector = widgets.HTML("""
        <div style='margin-bottom: 20px; display: flex; align-items: center; gap: 10px;'>
            <span style='font-weight: 600; color: #2c3e50;'>Plant:</span>
            <select style='padding: 8px 12px; border-radius: 8px; border: 1px solid #ddd; background: white; font-family: inherit; color: #2c3e50;'>
                <option>Monstera Deliciosa</option>
                <option>Snake Plant</option>
            </select>
        </div>
        """)

        # Gauges
        # Get sensors for plant_01 default
        plant = PLANTS_DATA["plant_01"]
        plant_sensors = []
        for sid in plant['sensor_ids'].values():
            if sid in SENSORS_DATA:
                plant_sensors.append((sid, SENSORS_DATA[sid]))

        gauge_widgets = []
        for sid, s in plant_sensors:
            # Closure for callback
            def on_click(b, sid=sid):
                show_details(sid)

            # Create gauge with callback
            gauge_card = create_gauge(s, on_click)
            gauge_widgets.append(gauge_card)

        top_row = widgets.GridBox(gauge_widgets, layout=widgets.Layout(grid_template_columns='1fr 1fr 1fr', grid_gap='20px', margin='0 0 20px 0'))

        # Bottom Row
        chart = create_history_chart({})
        summary = create_summary_card({})

        bottom_row = widgets.GridBox([chart, summary], layout=widgets.Layout(grid_template_columns='3fr 1fr', grid_gap='20px'))

        content.clear_output()
        with content:
            display(widgets.VBox([plant_selector, top_row, bottom_row]))

    def show_details(sid):
        nonlocal view_mode, selected_sensor_id
        view_mode = "details"
        selected_sensor_id = sid
        sensor = SENSORS_DATA[sid]

        # Back Button
        back_btn = widgets.Button(description="← Back to Sensors", layout=widgets.Layout(width='150px', margin='0 0 20px 0'))
        back_btn.on_click(lambda b: show_list())

        # Components
        header = create_sensor_header(sensor, sid)

        # Grid 1: Realtime + Thresholds
        c1 = create_realtime_card(sensor)
        c2 = create_thresholds_card(sensor)
        grid1 = widgets.GridBox([c1, c2], layout=widgets.Layout(grid_template_columns='1fr 1fr', grid_gap='20px', margin='0 0 20px 0'))

        # Grid 2: Chart
        chart = create_single_sensor_chart(sensor)

        # Grid 3: MQTT + Metadata
        c3 = create_mqtt_card(sensor)
        c4 = create_metadata_card(sensor)
        grid3 = widgets.GridBox([c3, c4], layout=widgets.Layout(grid_template_columns='1fr 1fr', grid_gap='20px', margin='20px 0 0 0'))

        content.clear_output()
        with content:
            display(widgets.VBox([back_btn, header, grid1, chart, grid3]))

    # Initial render
    show_list()

    return content

# @title Analysis Page

# Components
def create_image_upload_card():
    return widgets.HTML("""
    <div class='card'>
        <div class='card-title'>Plant Image</div>
        <div style='position: relative; background: #d5f5e3; border-radius: 12px; height: 300px; display: flex; align-items: center; justify-content: center; font-size: 80px; margin-bottom: 20px; overflow: hidden;'>
            🌿
            <!-- Overlay Icons -->
        </div>
        <div style='display: flex; gap: 10px; margin-bottom: 10px;'>
            <button class='btn btn-primary btn-full'>⬆ Upload Image</button>
            <button class='btn btn-outline btn-full'>📷 Take Photo</button>
        </div>
        <div style='text-align: center; font-size: 11px; color: #95a5a6;'>
            Supported formats: JPG, PNG. Maximum size: 5MB.
        </div>
    </div>
    """)

def create_results_card(data):
    issues_html = ""
    for issue in data['issues']:
        severity_color = "#e74c3c" if issue['severity'] == "High" else "#f1c40f" if issue['severity'] == "Medium" else "#3498db"
        issues_html += f"""
        <div style='background: {issue['bg']}; border-left: 4px solid {issue['color']}; padding: 12px; border-radius: 8px; margin-bottom: 10px;'>
            <div style='display: flex; justify-content: space-between; align-items: flex-start;'>
                <div style='font-weight: 600; color: #2c3e50; display: flex; align-items: center; gap: 8px;'>
                    <span>{issue['icon']}</span> {issue['title']}
                </div>
                <div style='font-size: 10px; font-weight: 600; color: white; background: {severity_color}; padding: 2px 8px; border-radius: 10px;'>{issue['severity']}</div>
            </div>
            <div style='font-size: 13px; color: #7f8c8d; margin-top: 4px;'>{issue['desc']}</div>
        </div>
        """

    recs_html = ""
    for rec in data['recommendations']:
        recs_html += f"<li>{rec}</li>"

    return widgets.HTML(f"""
    <div class='card'>
        <div style='display: flex; justify-content: space-between; align-items: center; margin-bottom: 16px;'>
            <div class='card-title' style='margin-bottom: 0;'>Analysis Results</div>
            <div style='font-size: 11px; color: #95a5a6;'>Last analyzed: 2 minutes ago</div>
        </div>

        <div style='margin-bottom: 20px;'>
            <div style='font-size: 12px; color: #7f8c8d; margin-bottom: 8px; text-transform: uppercase; letter-spacing: 0.5px;'>Detected Issues</div>
            {issues_html}
        </div>

        <div style='margin-bottom: 20px;'>
            <div style='font-size: 12px; color: #7f8c8d; margin-bottom: 8px; text-transform: uppercase; letter-spacing: 0.5px;'>Confidence</div>
            <div style='display: flex; align-items: center; gap: 10px;'>
                <div style='flex: 1; height: 16px; background: #eee; border-radius: 8px; overflow: hidden; position: relative;'>
                    <div style='width: {data['confidence']}%; height: 100%; background: #2ecc71;'></div>
                    <div style='position: absolute; top: 0; left: 0; width: 100%; height: 100%; display: flex; align-items: center; justify-content: center; font-size: 10px; color: white; font-weight: bold; text-shadow: 0 0 2px rgba(0,0,0,0.5);'>
                        {data['confidence']}%
                    </div>
                </div>
            </div>
        </div>

        <div>
            <div style='font-size: 12px; color: #7f8c8d; margin-bottom: 8px; text-transform: uppercase; letter-spacing: 0.5px;'>Recommendations</div>
            <ul style='padding-left: 20px; font-size: 14px; color: #2c3e50; line-height: 1.6;'>
                {recs_html}
            </ul>
        </div>

        <div style='margin-top: 15px;'>
             <button class='btn btn-outline btn-full' style='border-style: dashed; color: #3498db; border-color: #3498db;'>✨ Ask AI About This Result</button>
        </div>

        <div style='display: flex; gap: 10px; margin-top: 20px;'>
            <button class='btn btn-primary btn-full'>Run New Analysis</button>
            <button class='btn btn-outline btn-full'>📄 Generate PDF</button>
        </div>
    </div>
    """)

def create_history_card(data):
    items = ""
    for item in data['history']:
        items += f"""
        <div style='display: flex; gap: 10px; padding: 10px; border-bottom: 1px solid #eee; align-items: center; cursor: pointer;'>
            <div style='width: 40px; height: 40px; background: #f0f0f0; border-radius: 6px; display: flex; align-items: center; justify-content: center; font-size: 20px;'>
                {item['thumb']}
            </div>
            <div>
                <div style='font-size: 12px; color: #95a5a6;'>{item['date']}</div>
                <div style='font-size: 13px; font-weight: 500; color: #2c3e50;'>{item['summary']}</div>
            </div>
        </div>
        """

    return widgets.HTML(f"""
    <div class='card'>
        <div class='card-title'>History</div>
        <div style='display: flex; flex-direction: column;'>
            {items}
            <div style='padding: 10px; text-align: center; font-size: 12px; color: #3498db; cursor: pointer;'>View All History</div>
        </div>
    </div>
    """)

# Render
def render_analysis():
    # State
    current_plant_id = "plant_01"

    content = widgets.Output()

    def update_view(change=None):
        nonlocal current_plant_id
        if change:
            current_plant_id = change['new']

        # Get data for selected plant
        data = ANALYSIS_DATA.get(current_plant_id, ANALYSIS_DATA["plant_01"])

        c1 = create_image_upload_card()
        c2 = create_results_card(data['latest'])
        c3 = create_history_card(data)

        # Layout: Left column (Upload + History), Right column (Results)
        left_col = widgets.VBox([c1, c3], layout=widgets.Layout(grid_gap='20px'))

        grid = widgets.GridBox([left_col, c2], layout=widgets.Layout(grid_template_columns='1fr 2fr', grid_gap='20px'))

        content.clear_output()
        with content:
            display(grid)

    # Plant Selector
    selector_options = [(p['name'], k) for k, p in PLANTS_DATA.items()]
    selector = widgets.Dropdown(options=selector_options, value="plant_01", layout=widgets.Layout(width='300px'))
    selector.observe(update_view, names='value')

    plant_selector_ui = widgets.HBox(
        [widgets.HTML("<span style='font-weight:600; color:#2c3e50; margin-right:10px;'>Plant:</span>"), selector],
        layout=widgets.Layout(margin='0 0 20px 0')
    )

    # Initial render
    update_view()

    return widgets.VBox([plant_selector_ui, content])

# @title Chat Page

# Data
CHAT_HISTORY = [
    {"role": "ai", "content": "Hello! I'm your AI plant assistant. I can help you with plant care advice, diagnose issues, and answer questions about your Monstera. How can I help you today?"},
    {"role": "user", "content": "Why are some of my leaves turning yellow?"},
    {"role": "ai", "content": """Based on your current sensor readings (moisture at 65%), yellowing leaves could indicate:
    <ul style='margin: 5px 0 5px 20px;'>
        <li>Overwatering - though your levels look okay</li>
        <li>Natural aging of lower leaves (normal)</li>
        <li>Nitrogen deficiency - consider fertilizing</li>
    </ul>
    I'd recommend checking if it's only the older, lower leaves. If so, this is natural!"""}
]

CONTEXT_DATA = {
    "moisture": "65%",
    "temperature": "22°C",
    "plant_type": "Monstera"
}

SUGGESTED_QUESTIONS = [
    "How often should I water?",
    "Best fertilizer schedule?",
    "Optimal light conditions?",
    "Common pest problems?"
]

# Components
def create_chat_area(messages):
    chat_html = ""
    for msg in messages:
        if msg['role'] == 'ai':
            chat_html += f"""
            <div style='display: flex; gap: 12px; margin-bottom: 20px;'>
                <div style='width: 32px; height: 32px; background: #2ecc71; border-radius: 50%; display: flex; align-items: center; justify-content: center; color: white; flex-shrink: 0;'>🤖</div>
                <div style='background: #e8f8f5; padding: 12px 16px; border-radius: 0 12px 12px 12px; max-width: 80%; color: #2c3e50; font-size: 14px; line-height: 1.5;'>
                    {msg['content']}
                </div>
            </div>
            """
        else:
            chat_html += f"""
            <div style='display: flex; justify-content: flex-end; margin-bottom: 20px;'>
                <div style='background: #2ecc71; color: white; padding: 12px 16px; border-radius: 12px 12px 0 12px; max-width: 80%; font-size: 14px;'>
                    {msg['content']}
                </div>
            </div>
            """

    return widgets.HTML(f"""
    <div class='card' style='height: 600px; display: flex; flex-direction: column;'>
        <div class='card-title'>AI Plant Assistant</div>
        <div style='flex: 1; overflow-y: auto; padding-right: 10px;'>
            {chat_html}
        </div>
        <div style='margin-top: 20px; display: flex; gap: 10px;'>
            <input type='text' placeholder='Ask me anything about your plant...' style='flex: 1; padding: 10px 15px; border: 1px solid #ddd; border-radius: 8px; outline: none;'>
            <button class='btn btn-primary' style='width: 40px; padding: 0;'>➤</button>
        </div>
    </div>
    """)

def create_context_card_chat(data):
    return widgets.HTML(f"""
    <div class='card'>
        <div class='card-title'>Plant Context</div>
        <div style='margin-bottom: 15px;'>
            <div style='font-size: 12px; color: #7f8c8d;'>Moisture</div>
            <div class='status-badge badge-success' style='display: inline-block; margin-top: 4px;'>{data['moisture']}</div>
        </div>
        <div style='margin-bottom: 15px;'>
            <div style='font-size: 12px; color: #7f8c8d;'>Temperature</div>
            <div class='status-badge badge-success' style='display: inline-block; margin-top: 4px;'>{data['temperature']}</div>
        </div>
        <div>
            <div style='font-size: 12px; color: #7f8c8d;'>Plant Type</div>
            <div style='background: #eee; padding: 4px 8px; border-radius: 12px; font-size: 12px; display: inline-block; margin-top: 4px;'>{data['plant_type']}</div>
        </div>
    </div>
    """)

def create_suggestions_card(questions):
    btns = ""
    for q in questions:
        btns += f"<button class='btn btn-outline btn-full' style='margin-bottom: 8px; text-align: left; justify-content: flex-start; font-weight: 400;'>{q}</button>"

    return widgets.HTML(f"""
    <div class='card'>
        <div class='card-title'>Suggested Questions</div>
        {btns}
    </div>
    """)

# Render
def render_chat():
    chat_area = create_chat_area(CHAT_HISTORY)

    # Sidebar
    context = create_context_card_chat(CONTEXT_DATA)
    suggestions = create_suggestions_card(SUGGESTED_QUESTIONS)
    sidebar = widgets.VBox([context, suggestions], layout=widgets.Layout(grid_gap='20px'))

    grid = widgets.GridBox([chat_area, sidebar], layout=widgets.Layout(grid_template_columns='3fr 1fr', grid_gap='20px'))

    return grid

# @title Rewards Page

# Data
USER_LEVEL = {
    "level": 12,
    "current_xp": 2450,
    "next_level_xp": 3000,
    "next_level_remaining": 550
}

MISSIONS = [
    {"task": "Check sensors 3 times", "progress": "3/3", "done": True},
    {"task": "Water your plant", "progress": "0/1", "done": False},
    {"task": "Upload plant photo", "progress": "0/1", "done": False}
]

ACHIEVEMENTS = [
    {"name": "First Plant", "icon": "🌱", "earned": True},
    {"name": "Week Streak", "icon": "💧", "earned": True},
    {"name": "Photo Pro", "icon": "📷", "earned": True},
    {"name": "Expert", "icon": "🏆", "earned": False},
    {"name": "Perfect Month", "icon": "⭐", "earned": False},
    {"name": "Perfectionist", "icon": "🎯", "earned": False}
]

STREAK_DATA = {
    "days": ["✓", "✓", "✓", "✓", "✓", "○", "○"],
    "count": 5
}

# Components
def create_level_card(data):
    percent = int((data['current_xp'] / data['next_level_xp']) * 100)

    return widgets.HTML(f"""
    <div class='card'>
        <div class='card-title'>Your Level</div>
        <div style='display: flex; align-items: center; gap: 20px;'>
            <div style='width: 80px; height: 80px; background: #2ecc71; border-radius: 50%; display: flex; flex-direction: column; align-items: center; justify-content: center; color: white; box-shadow: 0 4px 10px rgba(46, 204, 113, 0.3);'>
                <div style='font-size: 24px; font-weight: 700;'>{data['level']}</div>
                <div style='font-size: 12px;'>Level</div>
            </div>
            <div style='flex: 1;'>
                <div style='display: flex; justify-content: space-between; font-size: 14px; margin-bottom: 8px;'>
                    <span style='font-weight: 600;'>{data['current_xp']:,} XP</span>
                    <span style='color: #7f8c8d;'>{data['next_level_xp']:,} XP</span>
                </div>
                <div style='height: 8px; background: #eee; border-radius: 4px; overflow: hidden;'>
                    <div style='width: {percent}%; height: 100%; background: #2ecc71;'></div>
                </div>
                <div style='font-size: 12px; color: #7f8c8d; margin-top: 8px;'>{data['next_level_remaining']} XP to Level {data['level'] + 1}</div>
            </div>
        </div>
    </div>
    """)

def create_missions_card(missions):
    rows = ""
    for m in missions:
        bg = "#d5f5e3" if m['done'] else "transparent"
        icon = "⚡" if m['done'] else "◎"
        color = "#27ae60" if m['done'] else "#2c3e50"

        rows += f"""
        <div style='display: flex; justify-content: space-between; align-items: center; padding: 12px; border-radius: 8px; background: {bg}; margin-bottom: 10px;'>
            <div style='display: flex; align-items: center; gap: 10px; color: {color};'>
                <span>{icon}</span> {m['task']}
            </div>
            <div style='font-size: 12px; font-weight: 600; color: {color}; opacity: 0.7;'>{m['progress']}</div>
        </div>
        """

    return widgets.HTML(f"""
    <div class='card'>
        <div class='card-title'>Daily Missions</div>
        {rows}
    </div>
    """)

def create_achievements_card(badges):
    grid_items = ""
    for b in badges:
        opacity = "1" if b['earned'] else "0.4"
        bg = "#d5f5e3" if b['earned'] else "#f8f9fa"

        grid_items += f"""
        <div style='background: {bg}; border-radius: 12px; padding: 15px; text-align: center; opacity: {opacity};'>
            <div style='font-size: 24px; margin-bottom: 5px;'>{b['icon']}</div>
            <div style='font-size: 11px; font-weight: 600; color: #2c3e50;'>{b['name']}</div>
        </div>
        """

    return widgets.HTML(f"""
    <div class='card'>
        <div class='card-title'>Recent Achievements</div>
        <div style='display: grid; grid-template-columns: repeat(3, 1fr); gap: 10px;'>
            {grid_items}
        </div>
    </div>
    """)

def create_streak_card(data):
    day_html = ""
    for d in data['days']:
        bg = "#d5f5e3" if d == "✓" else "#f8f9fa"
        color = "#27ae60" if d == "✓" else "#bdc3c7"
        day_html += f"<div style='width: 30px; height: 30px; background: {bg}; border-radius: 8px; display: flex; align-items: center; justify-content: center; color: {color}; font-weight: bold;'>{d}</div>"

    return widgets.HTML(f"""
    <div class='card' style='display: flex; justify-content: space-between; align-items: center;'>
        <div>
            <div style='font-weight: 600; color: #2c3e50; display: flex; align-items: center; gap: 10px;'>
                <span style='font-size: 24px; color: #2ecc71;'>🎖️</span> Daily Care Streak
            </div>
            <div style='font-size: 12px; color: #7f8c8d; margin-top: 4px;'>Keep it up! Your plant is thriving.</div>
        </div>
        <div style='display: flex; gap: 8px;'>
            {day_html}
        </div>
        <div style='background: #e8f8f5; padding: 6px 12px; border-radius: 20px; color: #27ae60; font-weight: 700;'>
            {data['count']} Days 🔥
        </div>
    </div>
    """)

# Render
def render_rewards():
    c1 = create_level_card(USER_LEVEL)
    c2 = create_missions_card(MISSIONS)
    c3 = create_achievements_card(ACHIEVEMENTS)

    top_row = widgets.GridBox([c1, c2, c3], layout=widgets.Layout(grid_template_columns='1fr 1fr 1fr', grid_gap='20px', margin='0 0 20px 0'))

    streak = create_streak_card(STREAK_DATA)

    return widgets.VBox([top_row, streak])

# @title Alerts Page

# Data
ALERTS_LIST = [
    {"title": "Soil moisture declining", "msg": "Water recommended within 24 hours", "time": "2 hours ago", "severity": "warning", "action": "Water Now"},
    {"title": "Temperature drop detected", "msg": "Night temperature at 16°C, within acceptable range", "time": "5 hours ago", "severity": "info", "action": "View Details"},
    {"title": "Optimal conditions maintained", "msg": "All sensors reading in ideal range for 12 hours", "time": "12 hours ago", "severity": "success", "action": "Dismiss"},
    {"title": "Low light levels", "msg": "Consider moving plant closer to window", "time": "1 day ago", "severity": "warning", "action": "View Tips"}
]

# Components
def create_filters():
    severity = widgets.Dropdown(options=['All Severities', 'High', 'Medium', 'Low'], value='All Severities', layout=widgets.Layout(width='150px'))
    types = widgets.Dropdown(options=['All Types', 'Water', 'Light', 'Temperature'], value='All Types', layout=widgets.Layout(width='150px'))
    mark_read = widgets.Button(description="Mark All Read", layout=widgets.Layout(width='auto'))

    return widgets.HBox(
        [widgets.Label("Filters:", layout=widgets.Layout(margin='0 10px 0 0')), severity, types, mark_read],
        layout=widgets.Layout(
            background_color='white',
            padding='15px',
            border='1px solid #eee',
            border_radius='12px',
            margin='0 0 20px 0',
            justify_content='flex-start',
            align_items='center'
        )
    )

def create_alert_card(data):
    title = data['title']
    msg = data['msg']
    time = data['time']
    severity = data['severity']
    action_label = data.get('action')

    # Severity: warning, info, success
    colors = {
        "warning": {"bg": "#fef9e7", "border": "#f1c40f", "icon": "⚠️"},
        "info": {"bg": "#e8f8f5", "border": "#3498db", "icon": "ℹ️"},
        "success": {"bg": "#eafaf1", "border": "#27ae60", "icon": "✓"}
    }

    style = colors.get(severity, colors["info"])

    action_btn = ""
    if action_label:
        action_btn = f"<button style='background: white; border: 1px solid #ddd; padding: 6px 12px; border-radius: 6px; cursor: pointer; color: #2c3e50; font-size: 12px; margin-top: 10px;'>{action_label}</button>"

    return widgets.HTML(f"""
    <div style='background: {style['bg']}; border: 1px solid {style['bg']}; border-left: 4px solid {style['border']}; border-radius: 12px; padding: 20px; height: 100%; box-sizing: border-box; display: flex; flex-direction: column; justify-content: space-between;'>
        <div>
            <div style='display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 8px;'>
                <div style='font-weight: 600; color: #2c3e50; display: flex; gap: 10px; align-items: center;'>
                    <span style='font-size: 18px;'>{style['icon']}</span> {title}
                </div>
                <div style='font-size: 12px; color: #7f8c8d;'>{time}</div>
            </div>
            <div style='font-size: 13px; color: #7f8c8d; margin-left: 30px;'>{msg}</div>
        </div>
        <div style='margin-left: 30px;'>
            {action_btn}
        </div>
    </div>
    """)

# Render
def render_alerts():
    # Filters
    filters = widgets.HTML("""
    <div class='card' style='display: flex; justify-content: space-between; align-items: center; padding: 15px 20px; margin-bottom: 20px;'>
        <div style='display: flex; align-items: center; gap: 15px;'>
            <span style='font-weight: 600;'>Filters:</span>
            <select style='padding: 6px 12px; border: 1px solid #ddd; border-radius: 6px; background: #f8f9fa; outline: none;'><option>All Severities</option></select>
            <select style='padding: 6px 12px; border: 1px solid #ddd; border-radius: 6px; background: #f8f9fa; outline: none;'><option>All Types</option></select>
        </div>
        <button style='background: white; border: 1px solid #ddd; padding: 6px 12px; border-radius: 6px; cursor: pointer;'>Mark All Read</button>
    </div>
    """)

    # Alerts Grid
    alert_cards = [create_alert_card(a) for a in ALERTS_LIST]

    grid = widgets.GridBox(alert_cards, layout=widgets.Layout(grid_template_columns='1fr 1fr', grid_gap='20px'))

    return widgets.VBox([filters, grid])

# @title Main Application

class Navigation:
    def __init__(self, on_change):
        self.options = [
            ("🏠 Home", "home"),
            ("🌿 Plants", "plants"),
            ("📈 Sensors", "sensors"),
            ("📊 Analysis", "analysis"),
            ("💬 AI Chat", "chat"),
            ("🏆 Rewards", "rewards"),
            ("🔔 Alerts", "alerts")
        ]
        self.widget = widgets.ToggleButtons(
            options=self.options,
            value="home",
            style={'button_width': 'auto'},
            layout=widgets.Layout(width='auto')
        )
        self.widget.observe(lambda change: on_change(change['new']), names='value')
        self.widget.add_class('custom-nav')

class App:
    def __init__(self):
        self.content_area = widgets.Output()
        self.nav = Navigation(self.on_nav_change)

        # Header HTML (Brand part)
        self.brand = widgets.HTML("""
        <div class='brand'>
            <div class='brand-icon'>🌱</div>
            Smart Plant Monitor
        </div>
        """)

        # Combine Brand and Nav
        self.header = widgets.HBox(
            [self.brand, self.nav.widget],
            layout=widgets.Layout(
                justify_content='space-between',
                align_items='center',
                margin='0 0 20px 0',
                border_bottom='1px solid #eee',
                padding='0 0 10px 0'
            )
        )

        # Main Container
        self.container = widgets.VBox(
            [self.header, self.content_area]
        )
        self.container.add_class('dashboard-container')

    def on_nav_change(self, page_key):
        self.content_area.clear_output()
        with self.content_area:
            if page_key == "home":
                display(render_home())
            elif page_key == "plants":
                display(render_plants_page())
            elif page_key == "sensors":
                display(render_sensors())
            elif page_key == "analysis":
                display(render_analysis())
            elif page_key == "chat":
                display(render_chat())
            elif page_key == "rewards":
                display(render_rewards())
            elif page_key == "alerts":
                display(render_alerts())
            else:
                print(f"Page {page_key} not implemented yet.")

    def run(self):
        display(HTML(GLOBAL_CSS))

        # Add some specific CSS for the ToggleButtons to match the design
        display(HTML("""
        <style>
            .custom-nav .widget-toggle-button {
                background: transparent !important;
                border: none !important;
                color: #7f8c8d !important;
                font-weight: 500 !important;
                box-shadow: none !important;
            }
            .custom-nav .widget-toggle-button.mod-active {
                background: #d1f2eb !important;
                color: #27ae60 !important;
                border-radius: 20px !important;
                font-weight: 700 !important;
            }
        </style>
        """))

        display(self.container)
        # Load initial page
        self.on_nav_change("home")

if __name__ == "__main__":
    app = App()
    app.run()